[package]
name = "wise_units-ffi"
version = "0.16.0"
description = "FFI wrapper for wise_units"
repository = "https://github.com/agrian-inc/wise_units"
license = "MIT"
authors = ["Nicholas Smillie <nicholas@agrian.com>"]
edition = "2018"
publish = ["agrian-registry"]

[dependencies]
ffi_common = { version = "0.2", registry = "agrian-registry" }
wise_units = { version = "^0.16.0", registry = "agrian-registry" }

[build-dependencies]
cbindgen = "0.14"

[dev-dependencies]
approx = "0.3"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]
