[package]
name = "wise_units-atom_generator"
version = "0.17.0"
authors = ["Steve Loveless <steve@agrian.com>"]
edition = "2018"
publish = false

[dependencies]
handlebars = "4.0"
heck = "0.3"
lazy_static = "1.0"
log = "0.4"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
